ALTER TABLE Visit
ADD FOREIGN KEY (dinnerTableID) REFERENCES DinnerTable(dinnerTableID);

ALTER TABLE Visit
ADD FOREIGN KEY (custID) REFERENCES Customer(custID)
ON DELETE CASCADE;

ALTER TABLE Visit
ADD FOREIGN KEY (serverID) REFERENCES Server(serverID)
ON UPDATE CASCADE
ON DELETE SET NULL;